pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-16.04'

steps:
- task: Go@0
  displayName: 'go run'
  inputs:
    command: run
    arguments: 'test.go'
    workingDirectory: '$(system.defaultWorkingDirectory)/test'
